version: "3.7"
services:
  backend:
    build: ./backEnd
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  frontend:
    build: ./frontEnd
    ports:
      - 4200:80
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
